name: CI

on:
  push:
    path-ignore:
      - 'docs/**'
      - '**/README.org'
      - '**/README.md'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: run unit tests
        run: |
          yarn install
          yarn build
          yarn test
