on:
  push:
    branches:
      - master

name: Build and Publish

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 25
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Setup Node Env
        uses: actions/setup-node@v2
        with:
          node-version: 14
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      - name: Git Identity
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-action@users.noreply.github.com'
      - name: Install Modules
        run: yarn install --frozen-lockfile --check-files
      - name: Publish
        run: yarn publish:ci
